### ISSUE TITLE
VRay Fur support?

### ISSUE THREAD

**Issue by ultra-sonic** [ChaosGroup/vray-for-houdini#129]
Hi guys,

is there any chance to support rendering of Houdini Fur? Doing this through a procedural shader would be most appreciated. Tell me if you need a simple scene!

Cheers
Oli

**Comment by millag** [comment]
This should be fixed with #138. The only thing you'll need to do is set 'renderstyle' parameter to 'Direct' on the fur OBJ node.This will force Houdini to generate the stands as output render geometry in order for the exporter to pick it up. Also there are some additional rendering parameters you can add to the fur node through Edit Rendering Parameters->V-Ray->V-Ray Hair

**Comment by StrobFX** [comment]
Cool! 
![image](https://cloud.githubusercontent.com/assets/12475879/24969129/a43f8868-1f7d-11e7-8ca9-6b40f0b23206.png)
