### ISSUE TITLE
SettingsRTEngine_opencl_resizeTextures parameter causes shader failure

### ISSUE THREAD

**Issue by LukeLetellier** [ChaosGroup/vray-for-houdini#163]
On several different scenes, my shaders will render incorrectly due to this error message:

<a href="http://imgur.com/wSSAh7v"><img src="http://i.imgur.com/wSSAh7v.jpg" title="source: imgur.com" /></a>

I'm not rendering with OpenCl (or with RT), there aren't any textures in that shader, and it doesn't matter if I adjust that particular parameter to a different option - the shader fails to render correctly. 

Sometimes I'm able to restart the program to fix the problem. Other times I create a new Vray Material Output node, and that resolves the issue. 

Overall, the bug occurs sporadically & for no apparent reason - I can't recreate it at will.

I know that's not much help, but perhaps someone else has experienced something similar.

**Comment by millag** [comment]
I have a scene to reproduce this. Seems the reason is invalid value was saved on the .hip file for this parameter which is an expression. I'm not completely sure how it was created and why error on the ROP propagates to the shader network, but will investigate it. Try right click -> Delete Channels on the parameter and saving out the scene again.

**Comment by LukeLetellier** [comment]
Ok, will do. Thanks!
