### ISSUE TITLE
Velocity motion blur not working with packed objects

### ISSUE THREAD

**Issue by blented** [ChaosGroup/vray-for-houdini#216]
3 boxes, each moving up 1m / frame, from left to right: object-level motion, sop-level motion (transform node), same sop-level motion on a packed object:

![image](https://user-images.githubusercontent.com/1403171/28929937-2477f5dc-7826-11e7-8722-4e16b80d01ad.png)

It seems the standard Houdini velocity calculated by the Trail sop is too high, scaling the value by .18 got the velocity blur closer, but nothing outside of unpacking the object gets velocity blur to work on the 3rd box.

Test scene:
https://drive.google.com/file/d/0B-R03L35FWUSV1FjckMzNlBNU3M/view?usp=sharing

Windows 10, Houdini 16.0.600, vfh-34c33f4 (2017-08-03 nightly)

**Comment by bdancer** [comment]
This'll take some time to fix, there is smth in AppSDK that causing this...

**Comment by bravehamster** [comment]
hey @blented , thank for the feedback !

Regarding Bad news: points number 2 and 3 - the expression on the transforms was $F - settings this to $FF resolved the problem for me. Initially, I thought it's on our end but Mantra produces the same result as V-Ray for me when using $F.

I also wanted to ask for your opinion on the following -- the Geometry nodes have a checkbox called Geometry Velocity Blur which tells Mantra to use the v attribute instead of computing the motion blur based on the transforms/deforms of the object. For instance, in your test scene, the Trail SOP in the packed object, and the v attribute in the velocity object are not utilized when rendering with Mantra. Deleting those produces the exact same result - Mantra does the computation at rendertime. 

Would you prefer to have the same functionality where you need to explicitly tell the renderer to use the v?

**Comment by blented** [comment]
That's great! Apologies for the mistake on my end, glad it was an easy fix.  I updated the test scene and now get motion blur for everything but the packed object :)

https://drive.google.com/file/d/1AFLmjI0fAJ88nN0J3I5hEqZfecthNy0n/view?usp=sharing

I feel it would be good to support the Geometry Velocity Blur option, there are definitely cases where you want to explicitly specify "v" as opposed to allowing VRay to compute it (fluids, etc).

Will motion blur eventually be supported in IPR as well?  Thanks!

**Comment by bdancer** [comment]
> Will motion blur eventually be supported in IPR as well? 

Yes, that's pretty easy to add. I'll enable it right after slow packed export...

**Comment by bdancer** [comment]
@blented should work in the next build even without "v". To use "v" enable "Geometry Velocity Blur" ("geo_velocityblur").

**Comment by bdancer** [comment]
I hope this is resolved finally:
![issue_216 instancer_mb](https://user-images.githubusercontent.com/319784/43776816-b7cad6be-9a59-11e8-8dcb-a7eeb2879d7e.png)

**Comment by blented** [comment]
Working perfectly ❤️
