### ISSUE TITLE
Vray environment fog: How to use?

### ISSUE THREAD

**Issue by postcontrol** [ChaosGroup/vray-for-houdini#234]
Hi,

I was wondering how can I use environment fog and foggizmo? Can't find anything what takes effect input.

Cheers,
Matti Kaihola

**Comment by bravehamster** [comment]
I don't think it's implemented yet but since Houdini has awesome volumetric tools, you can simply export a piece of geometry as a VDB and use a VolumeGrid shader.

Just a couple of notes:
1) when exporting the vdb, give it a trailing number. For example, myVolume_01.vdb
2)  set the Color Gradient on the VolumeGrid shader to a color of your choice - by default it's a rainbow mix of colors and unfortunately, setting the Diffuse Input on the Smoke Color tab to Constant color does not work at the moment.
4) you need to reduce the smoke opacity to a very low value
3) keep in mind that you need to use the Render button on the V-Ray tab rather than the teapot icon on the Frame buffer to be certain that your changes will be exported. 

I'm not sure if this workflow can fully substitute the V-Ray environment fog so if there are any issues - please drop a message.

[I'm also uploading a working example file for you.
](
https://chaossw-my.sharepoint.com/personal/gosho_genchev_chaosgroup_com/_layouts/15/guestaccess.aspx?docid=08b0b051c137a41e391008d0973c5f3d8&authkey=AS8hAyykH0ES9WmWaR2bgE4
)

Cheers.

**Comment by bdancer** [comment]
I've added "Fog" node, simply add it to "V-Ray Environment" context.
