### ISSUE TITLE
various lights issues

### ISSUE THREAD

**Issue by ronald-a** [ChaosGroup/vray-for-houdini#313]
here are a couple of issues with lights:

1. the direct light has some weird cutoff that makes it position dependent (see attached scene)
2. every light should have a default shadow bias of 0.01 - 0.02 to avoid artifacts (take a close look at the sphere in the scene when the direct light is on)
3. when turning off "dome spherical", not the lower half of the dome sphere is turned off (-y) but the side(-z)is. I guess this is some sort of orientation issue (which might also be true for the orientation of applied maps). this bug is rather new.
4. it would also be great if the domelight could respect its rotation to position the environment texture.

Cheers,

Ronny

[vray4_light_issues.zip](https://github.com/ChaosGroup/vray-for-houdini/files/2192512/vray4_light_issues.zip)

**Comment by bravehamster** [comment]
1. We're using the LightDirect plugin instead of the MayaLightDirect. It also causes V-Ray to hang when rendering volumetrics for some reason. I've already logged this in hopes it will be replaced with MayaLightDirect. 
2. Good note, I'll do it, Thank you!
3. I'll log this, thanks for cathing. 
4. This should work in the latest nightly. I think the changes were pushed yesterday so if it doesn't, wait for next build :)

**Comment by ronald-a** [comment]
@bravehamster I tested this on the latest nightly. if 4. was pushed yesterday (and it doesn't work btw) maybe this is the reason 3. happened. seems somehow related.

**Comment by bravehamster** [comment]
Dome light rotation works for me with the latest nightly, maybe you've got an environment file pointing to a different build?

[Here's a video](https://drive.google.com/file/d/1ur8Oy6vN8qo1HlgUHmqZ6vkm4SL8UqK4/view?usp=sharing)

**Comment by ronald-a** [comment]
@bravehamster you are absolutly right. no idea why i had the impression it did not work.
